name: Deploy To AWS S3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      S3_BUCKET_NAME: ${{ github.event.inputs.environment == 'dev' && secrets.AWS_S3_DEV_BUCKET_NAME || secrets.AWS_S3_PROD_BUCKET_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v4.0.0
        with:
          folder: .
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          bucket-region: ${{ secrets.AWS_REGION }}
          delete-removed: true