name: Deploy To AWS S3

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check AWS Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID: ${#AWS_ACCESS_KEY_ID}"
          echo "AWS_SECRET_KEY: ${AWS_SECRET_KEY}"
          echo "AWS_REGION: ${AWS_REGION}"
          echo "AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}"
      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v4.0.0
        with:
          folder: .
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          bucket-region: ${{ secrets.AWS_REGION }}
          delete-removed: true