name: Dev To AWS S3

on:
  push:
    branches:
      - "develop"

jobs:
  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy To S3
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_DEV_BUCKET_NAME }}/ --delete